version: '3.7'

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fsw_barber
    volumes: 
      - fsw_barber_pg_data:/bitnami/postgresql  

volumes: 
  fsw_barber_pg_data: