import { Toaster } from 'sonner'
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'

import './globals.css'
import { Footer } from '@/components/footer'
import { AuthProvider } from '@/providers/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Barber | FSW',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <AuthProvider>
          {children}

          <Toaster richColors />
          <Footer />
        </AuthProvider>
      </body>
    </html>
  )
}
